// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJA9ga40yV_Q3hYFnUUctnKo33DZRFNeM',
    appId: '1:464372108399:android:0215a71f57a42e2af9119a',
    messagingSenderId: '464372108399',
    projectId: 'marketshopapp-b54f9',
    databaseURL: 'https://marketshopapp-b54f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'marketshopapp-b54f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kvW6CJn7VCuA_Ob4j-UZce3bCNNBgyY',
    appId: '1:464372108399:ios:ab223a5de2d01732f9119a',
    messagingSenderId: '464372108399',
    projectId: 'marketshopapp-b54f9',
    databaseURL: 'https://marketshopapp-b54f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'marketshopapp-b54f9.appspot.com',
    iosClientId: '464372108399-9rvfagpbiecokoefkk4r6lsqjosaqqcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketshopApp',
  );
}
